In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

In [4]:
arr

array([1, 2, 3])

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.ndim

1

In [7]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.float32)

In [9]:
arr.dtype

dtype('float32')

In [10]:
arr = np.array([1, 2, 3])

In [11]:
arr.dtype

dtype('int64')

In [14]:
arr = np.float32(arr)

In [15]:
arr

array([1., 2., 3.], dtype=float32)

In [21]:
arr[1:]

array([2., 3.], dtype=float32)

In [22]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
])

In [23]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [24]:
arr2.ndim

2

In [25]:
arr2.dtype

dtype('int64')

In [27]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [33]:
arr2[2, 1]

8

In [39]:
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 10]
    ],
    [
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 100]
    ]
])

In [40]:
arr3.ndim

3

In [41]:
arr3

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,  10]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80, 100]]])

In [47]:
arr3[0, 1, 1]

5

In [48]:
l = [1, 2, 3]

In [51]:
l[2]

3

In [57]:
a = [1, 2, 3]
b = [4, 5, 6]
a = np.array(a)
b = np.array(b)

In [58]:
a

array([1, 2, 3])

In [59]:
b

array([4, 5, 6])

In [61]:
a*b

array([ 4, 10, 18])

In [62]:
a

array([1, 2, 3])

In [63]:
x = np.array([10])

In [65]:
x

array([10])

In [66]:
x*a

array([10, 20, 30])

In [67]:
a.shape

(3,)

In [70]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10],
    [75, 85, 105],
])

In [71]:
arr2.shape

(4, 3)

In [73]:
arr = np.array([1, 2, 3, 4, 5, 6])


In [74]:
arr

array([1, 2, 3, 4, 5, 6])

In [75]:
arr.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [76]:
zero_arr = np.zeros((4, 4))

In [77]:
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
ones_arr = np.ones((3, 4), dtype=np.int32)

In [81]:
ones_arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [82]:
ones_arr.dtype

dtype('int32')